# rOpenSci: tools for textmining open source science literature

## Abstract

1.  ABSTRACT PARAGRAPH 1

2.  ABSTRACT PARAGRAPH 2

3.  ABSTRACT PARAGRAPH 3

4.  ABSTRACT PARAGRAPH 4


#### Keywords 

R, software, API, PLoS, Springer, Pensoft, database, textmining, opensource

Introduction
============

Explosion of digital context online. But we need tools to facilitate textmining (i.e., rOpenSci)

Why text mine it.

How to text mine it.

Here, we introduce and give examples for textmining in R using rOpenSci packages, and related packages. 


Text mining sources
===================

[Describe open source data for text mining that we link to in R, and those we don't link to in R.]

There is increasing open source scientific literature content available online. However, only a small proportion of scientific journals provide access to their full content; whereas, many publishers provide open access to their metadata only (Table 1). 

#### Table 1. Sources of scientific literature, their content type provided via web services, whether rOpenSci has an R packages for the service, and where to find the API documentation.  

Data Provider                      | Content Type            | rOpenSci? | API Documentation
---------------------------------- | ---------------------   | --------- | -----------------
Public Library of Science (PLoS)   | Full text/altmetrics    | rplos     | http://api.plos.org/
Springer                           | Full text on OA content | rspringer | http://dev.springer.com/
Pensoft                            | Full text/altmetrics    | rpensoft  | http://bit.ly/KYP0Zi
Nature Publishing Group            | Metadata only           | No        | http://developers.nature.com/
Mendeley                           | Metadata only           | rmendeley | http://dev.mendeley.com/
DataCite                           | Metadata only           | rdatacite | http://oai.datacite.org/
Biodiversity Heritage Library      | Full content            | rbhl      | http://bit.ly/KYQ1Rd
Scopus (Elsevier)                  | Metadata only ????      | No        | http://bit.ly/J9S616

#### Table 2. Tools for text mining science literature. 

Tool           |  Platform            | Services              | URL
-------------- | -------------------- | --------------------- | ---------------------
PMC Miner      | Python               | PubMed                | http://bit.ly/L29ekY
rOpenSci       | R                    | See Table 1           | http://ropensci.org/
PMC Miner      | Python               | PubMed                | http://bit.ly/L29ekY
PMC Miner      | Python               | PubMed                | http://bit.ly/L29ekY
PMC Miner      | Python               | PubMed                | http://bit.ly/L29ekY
PMC Miner      | Python               | PubMed                | http://bit.ly/L29ekY
PMC Miner      | Python               | PubMed                | http://bit.ly/L29ekY
PMC Miner      | Python               | PubMed                | http://bit.ly/L29ekY
PMC Miner      | Python               | PubMed                | http://bit.ly/L29ekY
PMC Miner      | Python               | PubMed                | http://bit.ly/L29ekY
PMC Miner      | Python               | PubMed                | http://bit.ly/L29ekY
PMC Miner      | Python               | PubMed                | http://bit.ly/L29ekY


How to text mine from R: Three case studies
===========================================

Case study 1
------------


Case study 2
------------


Case study 3
------------


Conclusion
==========



Acknowledgements
================




# References


Appendix
========

### To read:
+ http://lintool.github.com/MapReduceAlgorithms/index.html
+ 